### ISSUE TITLE
IntelliSense not showing up when deps block is the last method in mix.exs

### ISSUE THREAD

**Issue by benlime** [benlime/vscode-hex-pm-intellisense#1]

**Comment by xmbhasin** [comment]
I believe the issue is with this line: https://github.com/benlime/vscode-hex-pm-intellisense/blob/affa5d1d67698b918e786a5580a22b61d8a84197/src/shouldProvide.ts#L23

There is an explicit check, `indexOfDepsEnd < indexOfNextFunctionHead`, that ensures that the deps function is not the last function in `mix.exs`. Removing that bit fixes the issue on my machine, but I'm not sure if this breaks anything else so I didn't edit it myself.

**Comment by benlime** [comment]
Yes, removing the line fixes it, but would enable the plugin for any functions defined after `deps`, too. 

I think the proper solution would be to detect only the end of the `deps` function block, but I'm not quite sure yet how to accomplish it. 

I dont have access to my computer for the next couple of days, but would appreciate any ideas, so that I can implement it asap.
